#!/bin/bash
# Pulumi Quick Start - Run This!

echo "🎯 PULUMI QUICK START"
echo "===================="
echo ""
echo "Статус подготовки:"
echo "✅ Service Account: aje7uo8bgb48c146bg79"
echo "✅ Folder ID:       b1gsfpff6nb6v1a4q5g8"
echo "✅ key.json:        terraform/key.json"
echo "✅ SSH key:         ~/.ssh/lab04_key"
echo "✅ Pulumi.dev.yaml: Настроена"
echo ""
echo "===================="
echo ""
echo "СЛЕДУЮЩИЕ ШАГИ:"
echo ""
echo "1️⃣ Добавить Pulumi в PATH:"
echo "   export PATH=\$HOME/.pulumi/bin:\$PATH"
echo ""
echo "2️⃣ Перейти в pulumi директорию:"
echo "   cd pulumi/"
echo "   source venv/bin/activate"
echo "   export YC_SERVICE_ACCOUNT_KEY_FILE='../terraform/key.json'"
echo ""
echo "3️⃣ Инициализировать stack:"
echo "   pulumi stack init dev"
echo ""
echo "4️⃣ Preview (посмотри что будет):"
echo "   pulumi preview"
echo ""
echo "5️⃣ Deploy (создай инфраструктуру):"
echo "   pulumi up"
echo ""
echo "6️⃣ Получить IP:"
echo "   pulumi stack output instance_public_ip"
echo ""
echo "7️⃣ Подключиться по SSH:"
echo "   ssh -i ~/.ssh/lab04_key ubuntu@\$(pulumi stack output instance_public_ip)"
echo ""
echo "8️⃣ Удалить (cleanup):"
echo "   pulumi destroy"
echo ""
echo "===================="
echo ""
echo "Для полного гайда смотри: PULUMI_TESTING_GUIDE.md"
echo ""
