---
# Handlers for docker role

- name: restart docker
  service:
    name: docker
    state: restarted
  listen: restart docker

- name: update apt cache
  apt:
    update_cache: yes
  listen: update apt cache
